apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: $projectId$-kustomization
  namespace: $k8sNamespace$
resources:
  - namespace.yaml
  - postgresql.yaml
  - postgresql-svc.yaml
  - $projectId$.yaml
  - $projectId$-svc.yaml
