apiVersion: v1
kind: Service
metadata:
  name: postgresql-svc
  labels:
    app: postgresql-a
spec:
  ports:
  - port: 5432
    name: postgresql-port
  clusterIP: None
  selector:
      app: postgresql-a