services:
  db:
    image: postgres
    restart: always
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    environment:
      - "POSTGRES_USER=docker"
      - "POSTGRES_PASSWORD=docker"
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
     image: johndoe/$projectId$

     links:
       - db
     depends_on:
       db:
        condition: service_healthy
     ports:
        - "8080:8080"
     environment:
      - "DATABASE_JDBC_URL=jdbc:postgresql://db:5432/$projectId$"
