---
apiVersion: v1
kind: Secret
metadata:
  name: git-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: git
  url: ssh://git@github.com:cheleb/$projectId$-gitops.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    CHANGE ME
    -----END OPENSSH PRIVATE KEY-----

  insecure: "false"
  enableLFS: "false"
